version: 2.1

workflows:
  build_and_test:
    jobs:
      - job1
      - job2
      - hold:
          type: approval
          requires:
            - job2

jobs:
  job1:
    docker:
      - image: google/cloud-sdk
    steps:
      - run:
          name: 1st job for unit tests
          command: echo "1st job"
  
  job2:
    docker:
      - image: google/cloud-sdk
    steps:
      - run:
          name: 2nd job for prospective merge
          command: echo "2nd job"

  hold:
    docker:
      - image: google/cloud-sdk
    steps:
      - run:
          name: 3rd job for intergration tests
          command: echo "3rd job"
