version: 2.1

workflows:
  unit_tests:
    jobs:
      - job1
  integration_tests:
    jobs:
      - job2
      - job3

parameters:
  run_integration_tests:
    type: boolean
    default: false

jobs:
  job1:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - run:
          name: 1st job for unit tests
          command: echo "1st job"
  job2:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - run:
          name: 2nd job for prospective merge
          command: echo "2nd job"
  job3:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - run: 
          name : 3rd job for integration tests
          command: |
            if [[ << pipeline.parameters.run_integration_tests >> == true ]]; then 
              echo << pipeline.parameters.run_integration_tests >>
            else
              echo "Not running integration tests"
              exit 0
            fi
