version: 2
workflows:
  build_and_test:
    jobs:
      - build
      - test

jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: 1st job
          command: echo "1st job"
  test:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: 2nd job
          command: echo "2nd job"