version: 2
jobs:
  build:
    working_directory: ~/mern-starter
    # The primary container is an instance of the first image listed. The job's commands run in this container.
    docker:
      - image: hello-world
    steps:
      - checkout
      - run:
          name: 1st job
          command: echo "1st job"
  test:
    docker:
      - image: hello-world
    steps:
      - checkout
      - run:
          name: 2nd job
          command: echo "2nd job"

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build