version: 2.1

parameters:
  run_integration_tests:
    type: boolean
    default: false

workflows:
  unit_tests:
    jobs:
      - job1
      
  integration_tests:
  - when:
      condition:
        equals: ['<< pipeline.parameters.run_integration_tests >>', true]
    jobs:
      - job2
      - job3

jobs:
  job1:
    docker:
      - image: google/cloud-sdk
    steps:
      - run:
          name: 1st job for unit tests
          command: echo "1st job"
  
  job2:
    docker:
      - image: google/cloud-sdk
    steps:
      - run:
          name: 2nd job for prospective merge
          command: echo "2nd job"

  job3:
    docker:
      - image: google/cloud-sdk
    steps:
      - run:
          name: 3rd job for intergration tests
          command: echo "3rd job"
