version: 2
workflows:
  build_and_test:
    jobs:
      - build
      - test

jobs:
  build:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - run:
          name: 1st job
          command: echo "1st job"
  test:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - run:
          name: 2nd job
          command: echo "2nd job"