version: 2.1

workflows:
  build_and_test:
    jobs:
      - job1
      - job2:
          type: approval

jobs:
  job1:
    docker:
      - image: google/cloud-sdk
    steps:
      - run:
          name: 1st job
          command: echo "1st job"
  
  job2:
    docker:
      - image: google/cloud-sdk
    steps:
      - run:
          name: 2nd job
          command: echo "2nd job"